- hosts: all
  become: true 
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: install php
      apt: name=php update_cache=yes state=latest

    - name: install libapache2-mod-php
      apt: name=libapache2-mod-php update_cache=yes state=latest

    - name: install php-cli
      apt: name=php-cli update_cache=yes state=latest
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
     

